title: some style, please # name of the site
author: Danny Summerlin # name of site's author
email: hello@summerlin.co # email of site's author
url: https://summerlin.co # root address of the site
# baseurl: "/some-style-please" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A light CSS, fast, minimalist Jekyll theme based on no-style-please.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: some-style-please # if you are using GitHub Pages, change it to remote_theme: dannysummerlin/some-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
